name: Build Portable Medi

on:
  push:        
    branches: [ main ] 

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Portable Python
        shell: pwsh
        run: |
          Invoke-WebRequest https://www.python.org/ftp/python/3.13.5/python-3.13.5-embed-amd64.zip -OutFile python-win.zip
          Expand-Archive python-win.zip -DestinationPath python-win

      - name: Configure _pth
        shell: pwsh
        run: |
          $pthFile = (Get-ChildItem python-win -Filter "python*._pth" | Select-Object -First 1).FullName
          $zipName = (Get-ChildItem python-win -Filter "python*.zip" | Select-Object -First 1).Name
          Set-Content -Path $pthFile -Value ("$zipName`n..`nlibs`nimport site")

      - name: Install pip
        shell: pwsh
        run: |
          Invoke-WebRequest https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
          python-win/python.exe get-pip.py
      
      - name: Install dependencies
        shell: pwsh
        run: if (Test-Path requirements.txt) { python-win/python.exe -m pip install -r requirements.txt --target python-win/libs }

      - name: Create portable launch file
        shell: pwsh
        run: Set-Content -Path launch-win.bat -Value ("@echo off`ncd /d ""%~dp0""`npython-win\python.exe run.py")

      - name: Create portable zip
        shell: pwsh
        run: |
          Remove-Item python-win.zip -Force -ErrorAction SilentlyContinue
          Remove-Item get-pip.py -Force -ErrorAction SilentlyContinue
          Compress-Archive -Path * -DestinationPath medi.zip

      - name: Upload to 'Latest' release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: medi.zip
          asset_name: medi.zip
          tag: latest
          release_name: Latest
          overwrite: true
          body: "Automated latest build for ${{ github.sha }}"